"""Seal the opened EventX v2.1 association-v1 audit and its exclusion ledger.

This command is intentionally write-once: it refuses to overwrite either output
unless the newly generated bytes are identical to the existing file.
"""

from __future__ import annotations

from collections import Counter
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
from typing import Any, Iterable

from eventx.settings import REPO_ROOT


AUDIT_ROOT = REPO_ROOT / "data" / "v2_1" / "association" / "v1_audit"
REVIEW = REPO_ROOT / "eventx" / "release" / "v2_1" / "eventx_v2_1_blind_review_completed.jsonl"
RULE_SOURCE = REPO_ROOT / "eventx" / "features" / "v2_1_association.py"
EXCLUSIONS = AUDIT_ROOT / "opened_pair_content_exclusions.jsonl"
MANIFEST = AUDIT_ROOT / "audit_freeze_manifest.json"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def relative(path: Path) -> str:
    return str(path.resolve().relative_to(REPO_ROOT.resolve()))


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open() as handle:
        for line_number, line in enumerate(handle, start=1):
            if not line.strip():
                continue
            value = json.loads(line)
            if not isinstance(value, dict):
                raise ValueError(f"{path}:{line_number} must be a JSON object")
            rows.append(value)
    return rows


def index(rows: Iterable[dict[str, Any]], field: str) -> dict[str, dict[str, Any]]:
    result: dict[str, dict[str, Any]] = {}
    for row in rows:
        key = str(row.get(field) or "")
        if not key or key in result:
            raise ValueError(f"missing or duplicate {field}: {key!r}")
        result[key] = row
    return result


def write_once(path: Path, payload: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        if path.read_bytes() != payload:
            raise SystemExit(f"refusing to overwrite frozen artifact: {path}")
        return
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_bytes(payload)
    temporary.replace(path)


def jsonl_bytes(rows: Iterable[dict[str, Any]]) -> bytes:
    return (
        "".join(json.dumps(row, sort_keys=True) + "\n" for row in rows)
    ).encode()


def main() -> None:
    preparation_path = AUDIT_ROOT / "association_audit_preparation_report.json"
    report_path = AUDIT_ROOT / "association_audit_report.json"
    blind_path = AUDIT_ROOT / "association_blind_review.jsonl"
    key_path = AUDIT_ROOT / "association_blind_key.jsonl"
    preparation = json.loads(preparation_path.read_text())
    report = json.loads(report_path.read_text())

    expected_rule_hash = preparation["input_hashes"][relative(RULE_SOURCE)]
    if sha256_file(RULE_SOURCE) != expected_rule_hash:
        raise SystemExit("v1 matcher source changed since audit preparation")
    if report.get("status") != "failed":
        raise SystemExit("expected the v1 audit status to be failed")
    if report.get("by_source", {}).get("news", {}).get("status") != "accepted":
        raise SystemExit("expected the news source audit to be accepted")
    if report.get("by_source", {}).get("kol", {}).get("status") != "failed":
        raise SystemExit("expected the KOL source audit to be failed")

    key = index(read_jsonl(key_path), "audit_id")
    blind = index(read_jsonl(blind_path), "audit_id")
    reviewed = index(read_jsonl(REVIEW), "audit_id")
    if not (set(key) == set(blind) == set(reviewed)):
        raise SystemExit("key, blind packet, and completed review IDs differ")

    exclusions = []
    for audit_id in sorted(key):
        keyed = key[audit_id]
        review_row = reviewed[audit_id]
        if any(
            review_row.get(field) != blind[audit_id].get(field)
            for field in (
                "audit_id",
                "category",
                "document_event_ts",
                "document_metadata",
                "document_source",
                "document_text",
                "market_question",
                "venue",
            )
        ):
            raise SystemExit(f"review mutated a blinded field for {audit_id}")
        exclusions.append(
            {
                "audit_id": audit_id,
                "content_hash": keyed["content_hash"],
                "doc_id": keyed["doc_id"],
                "market_id": keyed["market_id"],
                "pair_id": keyed["pair_id"],
                "source": keyed["source"],
            }
        )
    write_once(EXCLUSIONS, jsonl_bytes(exclusions))

    frozen_paths = [
        preparation_path,
        report_path,
        blind_path,
        key_path,
        REVIEW,
        AUDIT_ROOT / "association_candidate_pool.jsonl",
        AUDIT_ROOT / "market_specs.jsonl",
        AUDIT_ROOT / "kol_documents_predevelopment.jsonl",
        AUDIT_ROOT / "kol_market_assoc_predevelopment.jsonl",
        AUDIT_ROOT / "news_documents_predevelopment.jsonl",
        AUDIT_ROOT / "news_market_assoc_predevelopment.jsonl",
        RULE_SOURCE,
        EXCLUSIONS,
    ]
    counts = Counter(row["source"] for row in exclusions)
    manifest = {
        "association_rule": preparation["association_rule"],
        "audit_disposition": "opened_development_material_do_not_reuse_for_validation",
        "frozen_at": datetime.now(timezone.utc).isoformat(),
        "frozen_files": {
            relative(path): {"bytes": path.stat().st_size, "sha256": sha256_file(path)}
            for path in frozen_paths
        },
        "opened_exclusion_key": ["market_id", "content_hash"],
        "opened_rows": len(exclusions),
        "opened_rows_by_source": dict(sorted(counts.items())),
        "protocol_id": preparation["protocol_id"],
        "reuse_policy": (
            "All 300 reviewed market-content pairs are opened development data. "
            "Exclude them from every later blind audit by (market_id, content_hash); "
            "also reject matching pair_id values as a redundant guard."
        ),
        "status": "frozen_failed_development_audit",
    }
    payload = (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode()
    if MANIFEST.exists():
        existing = json.loads(MANIFEST.read_text())
        # The timestamp is provenance, not a reason to invalidate an idempotent rerun.
        manifest["frozen_at"] = existing.get("frozen_at")
        payload = (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode()
    write_once(MANIFEST, payload)
    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
